// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/RezaZahedi/Go-Gin/REST_api"
	"github.com/RezaZahedi/Go-Gin/database"
	"github.com/RezaZahedi/Go-Gin/product"
	"github.com/RezaZahedi/Go-Gin/user"
)

// Injectors from wire.go:

func InitProductAPI(db *database.BookDB) REST_api.ProductAPI {
	productRepository := product.ProvideProductRepository(db)
	productService := product.ProvideProductService(productRepository)
	productAPI := REST_api.ProvideProductAPI(productService)
	return productAPI
}

func InitUserAPI(db *database.UserDB) REST_api.UserAPI {
	userRepository := user.ProvideUserRepository(db)
	userService := user.ProvideUserService(userRepository)
	userAPI := REST_api.ProvideUserAPI(userService)
	return userAPI
}
