// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: fibo_model.proto

package fibo_model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GetFibonacciNumber service

type GetFibonacciNumberService interface {
	GenerateNumber(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type getFibonacciNumberService struct {
	c    client.Client
	name string
}

func NewGetFibonacciNumberService(name string, c client.Client) GetFibonacciNumberService {
	return &getFibonacciNumberService{
		c:    c,
		name: name,
	}
}

func (c *getFibonacciNumberService) GenerateNumber(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetFibonacciNumber.GenerateNumber", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetFibonacciNumber service

type GetFibonacciNumberHandler interface {
	GenerateNumber(context.Context, *Request, *Response) error
}

func RegisterGetFibonacciNumberHandler(s server.Server, hdlr GetFibonacciNumberHandler, opts ...server.HandlerOption) error {
	type getFibonacciNumber interface {
		GenerateNumber(ctx context.Context, in *Request, out *Response) error
	}
	type GetFibonacciNumber struct {
		getFibonacciNumber
	}
	h := &getFibonacciNumberHandler{hdlr}
	return s.Handle(s.NewHandler(&GetFibonacciNumber{h}, opts...))
}

type getFibonacciNumberHandler struct {
	GetFibonacciNumberHandler
}

func (h *getFibonacciNumberHandler) GenerateNumber(ctx context.Context, in *Request, out *Response) error {
	return h.GetFibonacciNumberHandler.GenerateNumber(ctx, in, out)
}
